name: Sugerir uma melhoria
description: Uma ideia para o projeto
labels: [enhancement]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Como você imagina a solução
    validations:
      required: true
